name: Build project
on: push

env:
  github_workspace: ${{ github.workspace }}

jobs:

  jula:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Collect required files
        continue-on-error: true
        id: collect-files
        run: |
          sudo apt update
          sudo apt install -y wget python3
          wget -P /tmp/jula https://raw.githubusercontent.com/MarshallBaby/JULA-GitHub-Action-Utils/master/collect-required-files.py
          python3 /tmp/jula/collect-required-files.py

      - name: Show files
        if: steps.collect-files.outcome == 'success'
        run: cat /tmp/jula/files_required.txt