name: Build project
on: push

env:
  github_workspace: ${{ github.workspace }}

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files
        run: |
          sudo apt update
          sudo apt install -y wget python3
          wget -P /tmp/jula https://raw.githubusercontent.com/MarshallBaby/JULA-GitHub-Action-Utils/master/is-jula-required.py
          python3 /tmp/jula/is-jula-required.py
