name: Build project
on: push

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Greeting
        run:
          echo github.workspace

      - name: List files
        run:
          ls ${{ github.workspace }}